general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: ''
    mtaBuildTool: 'cloudMbt'
    mtarName: '/home/ghassen/cloud-cf-helloworld-nodejs'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 's0019617342trial'
      space: 'Dev'
      credentialsId: 'CF_CREDENTIALSID'

