general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    dockerImage: 'ppiper/mta-archive-builder'
    mtaBuildTool: 'classic'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 's0019617342trial'
      space: 'Dev'
      credentialsId: 'CF_CREDENTIALSID'

