general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    mtaJarLocation: '/path/to/mta/jar/on/your/system
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 's0019617342trial'
      space: 'Dev'
      credentialsId: 'CF_CREDENTIALSID'

